# Generated by Django 4.2.3 on 2023-07-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=1, upload_to='user/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
