# Generated by Django 4.2.3 on 2023-07-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user_photo_alter_like_unique_together'),
        ('blog', '0005_comment_article'),
    ]

    operations = [
    ]
